// Package main processes embedded PNG glyph images to generate bitmasked
// pixel representations and their corresponding ASCII characters into a
// static Go source file.
package main

import (
	"bytes"
	"embed"
	"fmt"
	"go/format"
	"image/png"
	"log"
	"os"
	"path/filepath"
	"slices"
)

type bitChar struct {
	bitmap uint64
	char   byte
}

var set = map[string]byte{
	"./fslash.png":     '/',
	"./fslash-raw.png": '/',
	"./fslash-inv.png": '/',
	"./bslash.png":     '\\',
	"./bslash-raw.png": '\\',
	"./bslash-inv.png": '\\',
	"./comma.png":      ',',
	"./cap.png":        '^',
	"./pure.png":       '@',
	"./none.png":       ' ',
	"./underscore.png": '_',
	"./minus.png":      '-',
	"./plus.png":       '+',
	"./equal.png":      '=',
	"./vline.png":      'a',
	"./hline1.png":     '|',
	"./hline2.png":     '|',
}

//go:embed *.png
var bitmaps embed.FS

func main() {
	s := make([]bitChar, 0, len(set))
	for name, char := range set {
		rel, err := filepath.Rel(".", name)
		if err != nil {
			log.Fatal(err)
		}

		b, err := bitmaps.ReadFile(rel)
		if err != nil {
			log.Fatal(err)
		}

		img, err := png.Decode(bytes.NewReader(b))
		if err != nil {
			log.Fatal(err)
		}

		var i int

		var bitmap uint64

		for x := range 5 {
			for y := range 10 {
				c := img.At(x, y)
				r, _, _, _ := c.RGBA()
				if byte(r) > 127 {
					bitmap |= (1 << i)
				}
				i++
			}
		}
		s = append(s, bitChar{bitmap, char})
	}

	slices.SortStableFunc(s, func(a, b bitChar) int { return int(a.char) - int(b.char) })

	buf := bytes.NewBuffer(nil)

	fmt.Fprintf(buf, "// Code generated by bitmaps/create.go; DO NOT EDIT.\n\npackage main\n\n")

	fmt.Fprintf(buf, "var bitmaps = [%d]uint64{\n", len(s))
	for _, e := range s {
		fmt.Fprintf(buf, "\t0b%050b,\n", e.bitmap)
	}
	fmt.Fprintf(buf, "}\n\n")

	fmt.Fprintf(buf, "var chars = [%d]byte{\n", len(s))
	for _, e := range s {
		switch e.char {
		case '\'':
			fmt.Fprintf(buf, "\t'\\'',\n")
		case '\\':
			fmt.Fprintf(buf, "\t'\\\\',\n")
		default:
			fmt.Fprintf(buf, "\t'%c',\n", e.char)
		}
	}
	fmt.Fprintf(buf, "}\n")

	p, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("failed to format generated Go code: %v\nGenerated raw text:\n%s", err, buf.String())
	}

	err = os.WriteFile("bitmaps.go", p, 0o644)
	if err != nil {
		log.Fatalf("failed to write bitmaps.go: %v", err)
	}

	fmt.Printf("Successfully generated bitmaps.go with %d unique glyphs.\n", len(s))
}
